pg_replication:
  query: |
    SELECT
      CASE WHEN pg_is_in_recovery() THEN 1 ELSE 0 END as is_replica,
      pg_is_in_recovery() as in_recovery,
      pg_last_wal_receive_lsn() as receive_lsn,
      pg_last_wal_replay_lsn() as replay_lsn,
      pg_last_xact_replay_timestamp() as replay_timestamp
    FROM pg_stat_replication
  metrics:
    - is_replica:
        usage: "GAUGE"
        description: "Is this instance a replica"
    - in_recovery:
        usage: "GAUGE"
        description: "Is the instance in recovery mode"