version: '3.8'

services:
  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: social-network-app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/ib?currentSchema=ntwrk
      SPRING_DATASOURCE_USERNAME: ntwrk_ms
      SPRING_DATASOURCE_PASSWORD: ntwrk_ms
    depends_on:
      - db
    networks:
      - social-network-net

  db:
    image: postgres:15
    container_name: social-network-db
    environment:
      POSTGRES_DB: ib
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./postgres/init.sh:/docker-entrypoint-initdb.d/initdb.sh
      - postgres_data:/var/lib/postgresql/data
    networks:
      - social-network-net

volumes:
  postgres_data:

networks:
  social-network-net:
    driver: bridge