server:
  port: ${PORT_TO_EXPOSE:8081}
  forward-headers-strategy: framework

spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
  application:
    name: social-network
  main:
    allow-bean-definition-overriding: true
  datasource:
    master:
      driverClassName: org.postgresql.Driver
      url: ${MASTER_DATASOURCE_URL:jdbc:postgresql://localhost:5432/ib?currentSchema=ntwrk}
      username: ${MASTER_DATASOURCE_USERNAME:ntwrk_ms}
      password: ${MASTER_DATASOURCE_PASSWORD:ntwrk_ms}
      hikari:
        pool-name: Master-Hikari-Pool
        maximum-pool-size: 10
        connection-timeout: 30000
        idle-timeout: 600000
        max-lifetime: 1800000
    slave:
      driverClassName: org.postgresql.Driver
      url: ${SLAVE_DATASOURCE_URL:jdbc:postgresql://localhost:6543/ib?currentSchema=ntwrk}
      username: ${SLAVE_DATASOURCE_USERNAME:ntwrk_ms}
      password: ${SLAVE_DATASOURCE_PASSWORD:ntwrk_ms}
      hikari:
        pool-name: Slave-Hikari-Pool
        maximumPoolSize: 15
        connection-timeout: 30000
        idleTimeout: 600000
        maxLifetime: 1800000
        read-only: true  # Оптимизация для read-only соединений
  liquibase:
    enabled: false
    parameters:
      schema: ntwrk
      text_array_type: text[]
      json_type: JSONB
    change-log: classpath:/db/database_changelog.xml
    default-schema: ntwrk
    user: ${DATASOURCE_USER:ntwrk}
    password: ${DATASOURCE_PASSWORD:ntwrk}
  data:
    redis:
      database: 0
      sentinel:
        master: mymaster
        nodes: localhost:26379
      client-type: jedis
management:
  security:
    enabled: false
  health:
    ldap:
      enabled: false
    jms:
      enabled: false
  endpoint:
    startup:
      enabled: true
    health:
      enabled: true
    metrics:
      enabled: true
    prometheus:
      enabled: true
  prometheus:
    metrics:
      export:
        enabled: true
  endpoints:
    web.exposure.include: health,prometheus,startup
    enabled-by-default: false


social-network:
  jwt:
    expiration-timeout: 1200000
    secret-key: Mf9Cu5Y3wuZCBPTy3j3w8Xs43jfpCmgAB9FDq6GtZJg=


db:
  mode: redis

logging:
  level:
    dev.bd.work.socialnetwork: DEBUG
    org.springframework.security: DEBUG
    org.springframework.jdbc.core.JdbcTemplate: DEBUG
    com:
      zaxxer:
        hikari: INFO

debug: true